version: '3.8'

#./hookdeck login --cli-key 455y71q47egy4avxg9c08052wxu2akrd7pkoguzqbc7c26a31d
# ./hookdeck listen 8072 source --cli-path /monitor
# docker-compose pull && docker-compose up -d --force-recreate


# when moving to a folder, user these commands to clear everything up
#docker-compose down -v --remove-orphans
#docker volumes prune
#docker network prune

services:

  accounts_microservice:
    image: omarhammad97/accounts_microservice:latest
    depends_on:
      accounts_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - '8000:80'
    environment:
      DB_HOST: accounts_db
      DB_NAME: accounts_db
      DB_USERNAME: accounts_prod
      DB_PASSWORD: accounts_prod
    extends:
      file: common-config.yml
      service: microservices-common-configs

  cards_microservice:
    image: omarhammad97/cards_microservice:latest
    depends_on:
      cards_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - '8001:80'
    environment:
      DB_HOST: cards_db
      DB_NAME: cards_db
      DB_USERNAME: cards_prod
      DB_PASSWORD: cards_prod
    extends:
      file: common-config.yml
      service: microservices-common-configs

  loans_microservice:
    image: omarhammad97/loans_microservice:latest
    depends_on:
      loans_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - '8002:80'
    environment:
      SPRING_PROFILES_ACTIVE: 'prod'
      DB_HOST: loans_db
      DB_NAME: loans_db
      DB_USERNAME: loans_prod
      DB_PASSWORD: loans_prod
    extends:
      file: common-config.yml
      service: microservices-common-configs

  accounts_db:
    environment:
      POSTGRES_USER: accounts_prod
      POSTGRES_PASSWORD: accounts_prod
      POSTGRES_DB: accounts_db
    volumes:
      - accounts_db_data:/var/lib/postgresql/data
    extends:
      file: common-config.yml
      service: microservices-db-config

  cards_db:
    environment:
      POSTGRES_USER: cards_prod
      POSTGRES_PASSWORD: cards_prod
      POSTGRES_DB: cards_db
    volumes:
      - cards_db_data:/var/lib/postgresql/data
    extends:
      file: common-config.yml
      service: microservices-db-config

  loans_db:
    environment:
      POSTGRES_USER: loans_prod
      POSTGRES_PASSWORD: loans_prod
      POSTGRES_DB: loans_db
    volumes:
      - loans_db_data:/var/lib/postgresql/data
    extends:
      file: common-config.yml
      service: microservices-db-config

  configserver:
    image: omarhammad97/configserver:latest
    ports:
      - '8072:8071'
    depends_on:
      rabbitmq:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    extends:
      file: common-config.yml
      service: rabbitmq-config

volumes:
  accounts_db_data:
  cards_db_data:
  loans_db_data:

networks:
  bank_app:
    driver: "bridge"
