version: '3.8'

# docker-compose pull && docker-compose up -d --force-recreate
services:

  accounts_microservice:
    image: omarhammad97/accounts_microservice:latest
    restart: always
    depends_on:
      accounts_db:
        condition: service_healthy
    ports:
      - '8000:80'
    environment:
      ACTIVE_PROFILE: 'prod'
      DB_HOST: accounts_db
      DB_PORT: 5432
      DB_NAME: accounts_db
      DB_USERNAME: accounts_prod
      DB_PASSWORD: accounts_prod



  cards_microservice:
    image: omarhammad97/cards_microservice:latest
    restart: always
    depends_on:
      cards_db:
        condition: service_healthy
    ports:
      - '8001:80'
    environment:
      ACTIVE_PROFILE: 'prod'
      DB_HOST: cards_db
      DB_PORT: 5432
      DB_NAME: cards_db
      DB_USERNAME: cards_prod
      DB_PASSWORD: cards_prod



  loans_microservice:
    image: omarhammad97/loans_microservice:latest
    restart: always
    depends_on:
      loans_db:
        condition: service_healthy
    ports:
      - '8002:80'
    environment:
      ACTIVE_PROFILE: 'prod'
      DB_HOST: loans_db
      DB_PORT: 5432
      DB_NAME: loans_db
      DB_USERNAME: loans_prod
      DB_PASSWORD: loans_prod


  accounts_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: accounts_prod
      POSTGRES_PASSWORD: accounts_prod
      POSTGRES_DB: accounts_db
    volumes:
      - accounts_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U accounts_prod -d accounts_db" ]
      interval: 10s
      retries: 5
      start_period: 5s

  cards_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cards_prod
      POSTGRES_PASSWORD: cards_prod
      POSTGRES_DB: cards_db
    volumes:
      - cards_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cards_prod -d cards_db" ]
      interval: 10s
      retries: 5
      start_period: 5s

  loans_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: loans_prod
      POSTGRES_PASSWORD: loans_prod
      POSTGRES_DB: loans_db
    volumes:
      - loans_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U loans_prod -d loans_db" ]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  accounts_db_data:
  cards_db_data:
  loans_db_data:
