version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: loans-postgres-db
    restart: always
    environment:
      POSTGRES_USER: loans
      POSTGRES_PASSWORD: loans
      POSTGRES_DB: bank_loans
    ports:
      - "6002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
